[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

# Important: API routes configuration for Netlify
[[functions]]
  directory = ".netlify/functions"

# Redirect API routes to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}