# netlify.toml
[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Default fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404